language: python
dist: xenial  # required for Python >= 3.7
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - pypy
  - pypy3
matrix:
  include:
  - python: '3.7'
    services:
      - docker
    env: BUILD_SDIST=true
  - os: osx
    language: objective-c
    env: PYENV_VERSION=2.7.12
  - os: osx
    language: objective-c
    env: PYENV_VERSION=3.5.5
  - os: osx
    language: objective-c
    env: PYENV_VERSION=3.6.5
install:
- "./.travis/install.sh"
script:
- "./.travis/run.sh"
deploy:
  provider: releases
  api_key:
    secure: QiadMGAmtPw+Ut7LWqa3U/tImPIgiPH79mM9o8DGBckcacp9HkDYvCGuOjs5hZbCBBuQ6IAkikotS8iCSwHey1GK9jSDbpgKvVGiACdp8HNhitY8V/S3e1UukDlMeu+Q7vCJtynSGX0BJuiOQB8ZQyQ2HEZ7kMQgTLCEO1Uljhc=
  file:
    - dist/*.whl
    - dist/*.tar.gz
  file_glob: true
  on:
    repo: simplejson/simplejson
    tags: true
  skip_cleanup: true
